// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHordesWatchtower.Infrastructure.Persistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyHordesWatchtower.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(WatchtowerDbContext))]
    partial class WatchtowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyHordesWatchtower.Infrastructure.Persistance.Models.DbCitizenEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BatchTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Chaman")
                        .HasColumnType("boolean");

                    b.Property<long>("Charges")
                        .HasColumnType("bigint");

                    b.Property<string>("Constructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeathStatus")
                        .HasColumnType("integer");

                    b.Property<long>("Decoration")
                        .HasColumnType("bigint");

                    b.Property<long>("Defense")
                        .HasColumnType("bigint");

                    b.Property<bool>("Dehydrated")
                        .HasColumnType("boolean");

                    b.Property<bool>("DrugAddict")
                        .HasColumnType("boolean");

                    b.Property<int>("HomeLevel")
                        .HasColumnType("integer");

                    b.Property<int>("HordesId")
                        .HasColumnType("integer");

                    b.Property<bool>("Infected")
                        .HasColumnType("boolean");

                    b.Property<bool>("Injured")
                        .HasColumnType("boolean");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastConnectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OutsideTown")
                        .HasColumnType("boolean");

                    b.Property<int>("Profession")
                        .HasColumnType("integer");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Stars")
                        .HasColumnType("bigint");

                    b.Property<bool>("Terrified")
                        .HasColumnType("boolean");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.Property<long>("WellUses")
                        .HasColumnType("bigint");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CitizenEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
